estore/urls.py
from django.urls import path
from . import views


app_name = 'estore'


urlpatterns = [
    path('', views.home, name="home"),
    
    path('cart/', views.cart, name="cart"),
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('remove-from-cart/<int:cart_id>/', views.remove_from_cart, name="remove-from-cart"),
    path('increment-cart/<int:cart_id>/', views.increment_cart, name="increment-cart"),
    path('decrement-cart/<int:cart_id>/', views.decrement_cart, name="decrement-cart"),

    path('order/', views.create_order, name="order"),
    path('invoice/<order_id>/', views.invoice, name="invoice"),

    path('<slug:url_slug>/', views.category_products, name="category-products")
]

ezshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('estore.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

estore/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=50, verbose_name="Category Title")
    url_slug = models.SlugField(max_length=55, verbose_name="Category URL Slug")
    category_image = models.ImageField(upload_to='category', blank=True, null=True, verbose_name="Category Image")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ('-created_at', )

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=150, verbose_name="Product Title")
    product_image = models.ImageField(upload_to='product', blank=True, null=True, verbose_name="Product Image")
    price = models.DecimalField(max_digits=8, decimal_places=2)
    category = models.ForeignKey(Category, verbose_name="Product Categoy", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created_at', )

    def __str__(self):
        return self.title


class Cart(models.Model):
    product = models.ForeignKey(Product, verbose_name="Product", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1, verbose_name="Quantity")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")

    def __str__(self):
        return str(self.product)
    
    @property
    def total_price(self):
        return self.quantity * self.product.price     

estore/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from estore.models import Category, Product, Cart
from square.client import Client
import decimal


client = Client(
    access_token='{ACCESS_TOKEN}',
    environment='sandbox'
)

LOCATION_ID='{LOCATION_ID}'
CUSTOMER_ID = '{CUSTOMER_ID}'


def home(request):
    categories = Category.objects.filter()[:3]
    products = Product.objects.filter()[:8]
    context = {
        'categories': categories,
        'products': products,
    }
    return render(request, 'estore/index.html', context)


def category_products(request, url_slug):
    category = get_object_or_404(Category, url_slug=url_slug)
    products = Product.objects.filter(category=category)
    categories = Category.objects.all()
    context = {
        'category': category,
        'products': products,
        'categories': categories,
    }
    return render(request, 'estore/category_products.html', context)


def cart(request):
    cart_products = Cart.objects.all()

    amount = cart_total()
    shipping_amount = decimal.Decimal(0)

    context = {
        'cart_products': cart_products,
        'amount': amount,
        'shipping_amount': shipping_amount,
        'total_amount': amount + shipping_amount
    }
    return render(request, 'estore/cart.html', context)


def cart_total():
    amount = decimal.Decimal(0)
    cart_items = [item for item in Cart.objects.all()]
    if cart_items:
        for item in cart_items:
            temp_amount = (item.quantity * item.product.price)
            amount += temp_amount

    return amount


def add_to_cart(request):
    product_id = request.GET.get('prod_id')
    product = get_object_or_404(Product, id=product_id)

    if cart_total()+product.price < 50000:
        item_already_in_cart = Cart.objects.filter(product=product_id)
        if item_already_in_cart:
            cart_item = get_object_or_404(Cart, product=product_id)
            cart_item.quantity += 1
            cart_item.save()
        else:
            Cart(product=product).save()
    else:
        messages.error(request, 'Couldn\'t add item to the cart because orders worth more than $50,000 can\'t be created.')
    return redirect('estore:cart')


def remove_from_cart(request, cart_id):
    if request.method == 'GET':
        c = get_object_or_404(Cart, id=cart_id)
        c.delete()
    return redirect('estore:cart')


def increment_cart(request, cart_id):
    if request.method == 'GET':
        cart_item = get_object_or_404(Cart, id=cart_id)
        if cart_total()+cart_item.product.price < 50000:
            cart_item.quantity += 1
            cart_item.save()
        else:
            messages.error(request, 'Couldn\'t increment the quantity because orders worth more than $50,000 can\'t be created.')
    return redirect('estore:cart')


def decrement_cart(request, cart_id):
    if request.method == 'GET':
        cart_item = get_object_or_404(Cart, id=cart_id)
        if cart_item.quantity == 1:
            cart_item.delete()
        else:
            cart_item.quantity -= 1
            cart_item.save()
    return redirect('estore:cart')


def create_order(request):
    body = {
        "order": {
            "location_id": LOCATION_ID,
            "line_items": []
        }
    }

    cart = Cart.objects.all()
    for item in cart:
        newItem = {"name": item.product.title, "quantity": str(item.quantity), "base_price_money": {
            "amount": int(item.product.price*100), "currency": "USD"}}
        body['order']['line_items'].append(newItem)
        item.delete()
    result = client.orders.create_order(body)

    messages.success(
        request, 'The order has been created successfully using the Sqaure API.')
    context = {'order': result.body['order']}
    return render(request, 'estore/order.html', context)


def invoice(request, order_id):
    customer_id = CUSTOMER_ID
    draft_invoice = get_draft_invoice(order_id, customer_id)
    published_invoice = publish_invoice(
        draft_invoice['id'], draft_invoice['version'])

    messages.success(
        request, 'The invoice has been generated successfully using the Sqaure API.')
    context = {'invoice': published_invoice}
    return render(request, 'estore/invoice.html', context)


def get_draft_invoice(order_id, customer_id):

    result = client.invoices.list_invoices(location_id=LOCATION_ID)

    for invoice in result.body['invoices']:
        if invoice['order_id'] == order_id:
            return invoice

    result = client.invoices.create_invoice(
        body={
            "invoice": {
                "order_id": order_id,
                "primary_recipient": {
                    "customer_id": customer_id
                },
                "payment_requests": [{
                    "request_type": "BALANCE",
                    "due_date": "2050-01-14"
                }],
                "delivery_method": "EMAIL",
                "accepted_payment_methods": {
                    "card": True,
                    "square_gift_card": True
                }
            }
        }
    )

    return result.body['invoice']


def publish_invoice(id, version):
    result = client.invoices.publish_invoice(
        invoice_id=id,
        body={"version":  version}
    )
    return result.body['invoice']

estore/templates/estore/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block metatitle %}EZ Shop{% endblock metatitle %}</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="all,follow">
  <!-- Bootstrap CSS-->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
  <!-- Lightbox-->
  <link rel="stylesheet" href="{% static 'vendor/lightbox2/css/lightbox.min.css' %}">
  <!-- Range slider-->
  <link rel="stylesheet" href="{% static 'vendor/nouislider/nouislider.min.css' %}">
  <!-- Bootstrap select-->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
  <!-- Owl Carousel-->
  <link rel="stylesheet" href="{% static 'vendor/owl.carousel2/assets/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/owl.carousel2/assets/owl.theme.default.css' %}">
  <!-- Google fonts-->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap">
  <!-- theme stylesheet-->
  <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
  <!-- Custom stylesheet - for your changes-->
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>

<body>
  <div class="page-holder">
    {% include 'estore/navbar.html' %}

    {% block content %}

    {% endblock content %}

    {% include 'estore/scripts.html' %}

estore/templates/estore/cart.html
{% extends 'estore/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="container">
  <section class="py-5 bg-light">
    <div class="container">
      <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
        <div class="col-lg-6">
          <h1 class="h2 text-uppercase mb-0">Cart</h1>
        </div>
        <div class="col-lg-6 text-lg-right">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
              <li class="breadcrumb-item"><a href="{% url 'estore:home' %}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Cart</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>

  {% if messages %}
  {% for message in messages %}
  <div class="container mb-5 alert alert-danger alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
  {% endif %}


  {% if cart_products %}
  <section class="py-5">
    <h2 class="h5 text-uppercase mb-4">Shopping cart</h2>

    <div class="row">
      <div class="col-lg-8 mb-4 mb-lg-0">
        <div class="table-responsive mb-4">
          <table class="table">
            <thead class="bg-light">
              <tr>
                <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Product</strong></th>
                <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Price</strong></th>
                <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Quantity</strong></th>
                <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Total</strong></th>
                <th class="border-0" scope="col"> </th>
              </tr>
            </thead>
            <tbody>

              {% for cart_product in cart_products %}
              <tr>
                <th class="pl-0 border-0" scope="row">
                  <div class="media align-items-center">

                    <img src="{{cart_product.product.product_image.url}}" alt="{{cart_product.product.title}}"
                      width="70" />

                    <div class="media-body ml-3">
                      <strong class="h6">{{cart_product.product.title}}</strong>
                    </div>
                  </div>
                </th>
                <td class="align-middle border-0">
                  <p class="mb-0 small">${{cart_product.product.price|intcomma}}</p>
                </td>
                <td class="align-middle border-0">
                  <div class="border d-flex align-items-center justify-content-between px-3"><span
                      class="small text-uppercase text-gray headings-font-family">Quantity</span>
                    <div class="quantity">
                      <a href="{% url 'estore:decrement-cart' cart_product.id %}" class="dec-btn p-0 ml-2"><i
                          class="fas fa-minus"></i></a>
                      {% comment %} <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button> {% endcomment %}
                      <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text"
                        value="{{cart_product.quantity}}" />
                      {% comment %} <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button> {% endcomment %}
                      <a href="{% url 'estore:increment-cart' cart_product.id %}" class="inc-btn p-0"><i
                          class="fas fa-plus"></i></a>
                    </div>
                  </div>
                </td>
                <td class="align-middle border-0">
                  <p class="mb-0 small">${{cart_product.total_price|intcomma}}</p>
                </td>
                <td class="align-middle border-0"><a class="reset-anchor"
                    href="{% url 'estore:remove-from-cart' cart_product.id %}"><i
                      class="fas fa-trash-alt small text-muted"></i></a></td>
              </tr>
              {% endfor %}

            </tbody>
          </table>
        </div>
        <div class="bg-light px-4 py-3">
          <div class="row align-items-center text-center">
            <div class="col-md-6 mb-3 mb-md-0 text-md-left"><a class="btn btn-link p-0 text-dark btn-sm"
                href="{% url 'estore:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue Shopping</a>
            </div>
            <div class="col-md-6 text-md-right"><a class="btn btn-outline-dark btn-sm"
                href="{% url 'estore:order' %}">Create Order<i class="fas fa-long-arrow-alt-right ml-2"></i></a></div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="card border-0 rounded-0 p-lg-4 bg-light">
          <div class="card-body">
            <h5 class="text-uppercase mb-4">Cart total</h5>
            <ul class="list-unstyled mb-0">
              <li class="d-flex align-items-center justify-content-between"><strong
                  class="text-uppercase small font-weight-bold">Subtotal</strong><span
                  class="text-muted small">${{amount|intcomma}}</span></li>
              <li class="d-flex align-items-center justify-content-between"><strong
                  class="text-uppercase small font-weight-bold">Shipping Charge</strong><span class="text-muted small">+
                  ${{shipping_amount}}</span></li>
              <li class="border-bottom my-2"></li>
              <li class="d-flex align-items-center justify-content-between mb-4"><strong
                  class="text-uppercase small font-weight-bold">Total</strong><span>${{total_amount|intcomma}}</span>
              </li>
            </ul>

          </div>
        </div>
      </div>

    </div>
  </section>

  {% else %}

  <div class="text-center py-5">
    <h3 class="mb-3">Your cart is empty.</h3>
    <a href="{% url 'estore:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue Shopping</a>
  </div>

  {% endif %}

</div>
{% endblock content %}

estore/templates/estore/category_products.html
{% extends 'estore/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

<div class="container">
  <section class="py-5 bg-light">
    <div class="container">
      <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
        <div class="col-lg-6">
          <h1 class="h2 text-uppercase mb-0">Shop - {{category.title}}</h1>
        </div>
      </div>
    </div>
  </section>
  <section class="py-5">
    <div class="container p-0">
      <div class="row">
        <div class="col-lg-3 order-2 order-lg-1">
          <h5 class="text-uppercase mb-4">Categories</h5>

          {% if categories %}
          {% for cat in categories %}
          <a href="{% url 'estore:category-products' cat.url_slug %}">
            <div class="py-2 px-4 {% if category == cat %}bg-dark text-white {% else %}bg-light{% endif %} mb-3">
              <strong class="small text-uppercase font-weight-bold">{{cat.title}}</strong>
            </div>
          </a>
          {% endfor %}
          {% endif %}
        </div>


        <div class="col-lg-9 order-1 order-lg-2 mb-5 mb-lg-0">

          <div class="row" style="margin-top: 45px;">

            {% if products %}
            {% for product in products %}

            <div class="col-lg-4 col-sm-6">
              <div class="product text-center">
                <div class="mb-3 position-relative">

                  <div class="badge text-white badge-"></div>

                  <img class="img-fluid w-100" src="{{product.product_image.url}}" alt="{{product.title}}">

                  <div class="product-overlay">
                    <ul class="mb-0 list-inline">
                      <li class="list-inline-item m-0 p-0">
                        <form action="{% url 'estore:add-to-cart' %}">
                          <input type="hidden" name="prod_id" value="{{product.id}}" id="product_id">
                          <button type="submit" class="btn btn-sm btn-dark">Add to Cart</button>
                        </form>
                      </li>
                    </ul>
                  </div>
                </div>
                <h6>{{product.title}}</h6>
                <p class="small text-muted">${{product.price|intcomma}}</p>
              </div>
            </div>

            {% endfor %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock content %}

estore/templates/estore/index.html
{% extends 'estore/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <section class="pt-5 mt-5">
        <div class="row">
            {% if categories %}
            {% for category in categories %}

            <div class="col-md-4 mb-4 mb-md-0">
                <a class="category-item" href="{% url 'estore:category-products' category.url_slug %}">
                    <img class="img-fluid" src="{{ category.category_image.url }}" alt="{{ category.title }}">
                    <strong class="category-item-title">{{ category.title }}</strong>
                </a>
            </div>

            {% endfor %}
            {% endif %}
        </div>
    </section>

    <br>
</div>

{% endblock content %}

estore/templates/estore/invoice.html
{% extends 'estore/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="container">
    <section class="py-5 bg-light">
        <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
                <div class="col-lg-6">
                    <h1 class="h2 text-uppercase mb-0">Invoice</h1>
                </div>
            </div>
        </div>
    </section>

    <section class="py-5">
        {% if messages %}
        {% for message in messages %}
        <div class="container mb-5 alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}

        <h4 class="h4 text-uppercase">Invoice Details</h4>
        <br />
        <p class="ml-5 medium"><strong>Invoice Id:</strong> {{invoice.id}}</p>
        <p class="ml-5 medium"><strong>Order Id:</strong> {{invoice.order_id}}</p>
        <p class="ml-5 medium"><strong>Customer's Email Address:</strong> {{invoice.primary_recipient.email_address}}</p>
        {% widthratio invoice.payment_requests.0.computed_amount_money.amount 100 1 as payment %}
        <p class="ml-5 medium"><strong>Payment Request:</strong> ${{payment|intcomma}}.00</p>
        <p class="ml-5 medium"><strong>Payment URL:</strong> <a href="{{invoice.public_url}}">{{invoice.public_url}}</a></p>
        <p class="ml-5 medium"><strong>Status:</strong> {{ invoice.status}}</p>
    </section>
</div>
{% endblock content %}

estore/templates/estore/navbar.html
{% load static %}


<header class="header bg-white">
  <div class="container px-0 px-lg-3">
    <nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0"><a class="navbar-brand"
        href="{% url 'estore:home' %}"><span class="font-weight-bold text-uppercase text-dark">EZ Shop</span></a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'estore:home' %}">Home</a>
          </li>
          <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
            <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
              {% if categories_menu %}
              {% for cat_menu in categories_menu %}
              <a class="dropdown-item border-0 transition-link"
                href="{% url 'estore:category-products' cat_menu.url_slug %}">{{cat_menu.title}}</a>
              {% endfor %}
              {% endif %}
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'estore:cart' %}">
              <i class="fas fa-dolly-flatbed mr-1 text-gray"></i>Cart
              <small class="text-gray">({{cart_items.count}})</small>
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</header>

estore/templates/estore/order.html
{% extends 'estore/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="container">
    <section class="py-5 bg-light">
        <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
                <div class="col-lg-6">
                    <h1 class="h2 text-uppercase mb-0">Order</h1>
                </div>
            </div>
        </div>
    </section>

    <section class="py-5">
        {% if messages %}
        {% for message in messages %}
        <div class="container mb-5 alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
        
        
        <h4 class="h4 text-uppercase">Order Details</h4>
        <br />
        <p class="ml-5 medium"><strong>Order Id:</strong> {{order.id}}</p>
        {% widthratio order.total_money.amount 100 1 as amount %}
        <p class="ml-5 medium"><strong>Total Amount:</strong> ${{ amount|intcomma }}.00</p>
        <p class="ml-5 medium"><strong>Created At:</strong> {{ order.created_at}}</p>

        <br /><br />
        <h4 class="h4 text-uppercase">Items Details</h4>
        <br />

        <div class="row">
            <div class="col-lg-8 mb-4 mb-lg-0">
                <div class="table-responsive mb-4">
                    <table class="table">
                        <thead class="bg-light">
                            <tr>
                                <th class="border-0" scope="col"> <strong
                                        class="text-small text-uppercase">Name</strong></th>
                                <th class="border-0" scope="col"> <strong
                                        class="text-small text-uppercase">Price</strong></th>
                                <th class="border-0" scope="col"> <strong
                                        class="text-small text-uppercase">Quantity</strong></th>
                                <th class="border-0" scope="col"> <strong
                                        class="text-small text-uppercase">Total</strong></th>
                                <th class="border-0" scope="col"> </th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for item in order.line_items %}
                            <tr>
                                <td class="align-middle border-0">
                                    <p class="mb-0 small">{{item.name}}</p>
                                </td>
                                <td class="align-middle border-0">
                                    {% widthratio item.base_price_money.amount 100 1 as price %}
                                    <p class="mb-0 small">${{price|intcomma}}.00</p>
                                </td>
                                <td class="align-middle border-0">
                                    <p class="mb-0 small">{{item.quantity}}</p>
                                </td>
                                <td class="align-middle border-0">
                                    {% widthratio item.total_money.amount 100 1 as total %}
                                    <p class="mb-0 small">${{total|intcomma}}.00</p>
                                </td>

                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="bg-light px-4 py-3 text-center">
                    <a class="btn btn-outline-dark btn-lg" href="{% url 'estore:invoice' order.id %}"></i> Generate Invoice</a>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock content %}

estore/templates/estore/scripts.html
{% load static %}

<!-- JavaScript files-->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'vendor/lightbox2/js/lightbox.min.js' %}"></script>
      <script src="{% static 'vendor/nouislider/nouislider.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2/owl.carousel.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js' %}"></script>
      <script src="{% static 'js/front.js' %}"></script>
      
      <script>
        // ------------------------------------------------------- //
        //   Inject SVG Sprite - 
        //   see more here 
        //   https://css-tricks.com/ajaxing-svg-sprite/
        // ------------------------------------------------------ //
        function injectSvgSprite(path) {
        
            var ajax = new XMLHttpRequest();
            ajax.open("GET", path, true);
            ajax.send();
            ajax.onload = function(e) {
            var div = document.createElement("div");
            div.className = 'd-none';
            div.innerHTML = ajax.responseText;
            document.body.insertBefore(div, document.body.childNodes[0]);
            }
        }
        // this is set to BootstrapTemple website as you cannot 
        // inject local SVG sprite (using only 'icons/orion-svg-sprite.svg' path)
        // while using file:// protocol
        // pls don't forget to change to your domain :)
        injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg'); 
        
      </script>
      <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </div>
  </body>
</html>